#! /bin/bash

_rootdir=${_rootdir:-"$(dirname "$(readlink -f "$0")")"}
_ver="0.0.1-dev"
#_author="Wei Peng <me@1pengw.com>"

source "${_rootdir}/_shared_prologue"

#
# parameters
#
declare -i instance=${instance:-1}
declare target=${target:-help}
declare -i jobs=${jobs:-$((2+$(nproc)))}

# see also: http://nickdesaulniers.github.io/blog/2018/06/02/speeding-up-linux-kernel-builds-with-ccache/
declare -i deterministic=${deterministic:-0}

#
# getopt processing
#
function my_getopt_cont () {
    local n_shift=1 # number of shifts in the outer loop; shift by 1 by default
    case "$1" in
        -i|--instance)
            shift
            instance=$1
            n_shift=2
            ;;
        -t|--target)
            shift
            target=$1
            n_shift=2
            ;;
        -j|--jobs)
            shift
            jobs=$1
            n_shift=2
            ;;
        -d|--deterministic)
            deterministic=1
            n_shift=1
            ;;
    esac
    return $n_shift
}

my_getopt "i:t:j:d" "instance:,target:,jobs:,deterministic" "my_getopt_cont" "Make kernel instance." "$(
cat <<END
[-i|--instance=<instance>] [-t|--target=<target>] [-j|--jobs=<jobs>]
	[-d|--deterministic]
END
)" "$(
cat <<END
-i	--instance		Maximal number of kernel instances to prepare (default: $instance).
-t	--target		Makefile target to make (default: $target).
-j	--jobs		Number of parallel make jobs (default: $jobs).
-d	--deterministic		Deterministic build to leverage, e.g., ccache (default: $deterministic).
END
)" "$@"
ret=$?
eval set -- "$_getopt"
shift $ret 

# sanity check
vecho 0 <<END
$(
dumpparam <<END1
$(
for name in instance target jobs deterministic; do
    echo "$name=$(echo $(eval "echo \$_$name"))"
done
)
END1
)
END

build_dir="$LKHH_ARENA/build/$instance"

[[ -d "$build_dir" ]] || die 1 <<END
ERROR: $build_dir does not exist; consider "lkhh-init -i $instance" first.
END

vecho 0 <<END
make -C "$LKHH_LINUX" "O=$build_dir" -j $jobs "$@" "$target"
END

if (( deterministic > 0 )); then
    export KBUILD_BUILD_TIMESTAMP="1991-08-25" # Happy Birthday, Linux
fi

make -C "$LKHH_LINUX" "O=$build_dir" -j $jobs "$@" "$target"
