#! /bin/bash

_rootdir=${_rootdir:-"$(dirname "$(readlink -f "$0")")"}
_ver="0.0.1-dev"
#_author="Wei Peng <me@1pengw.com>"

source "${_rootdir}/_shared_prologue"

#
# parameters
#
declare -i instance=${instance:-1}
declare image=${image:-arch}

# "nokaslr" is critical for resolving symbols in debug
# see https://github.com/torvalds/linux/blob/master/Documentation/dev-tools/gdb-kernel-debugging.rst#setup
# alternative: CONFIG_RANDOMIZE_BASE=n
declare cmdline=${cmdline:-"nokaslr"}

declare system=${system:-"x86_64"}
declare gdb=${gdb:-"tcp::1234"}

#
# getopt processing
#
function my_getopt_cont () {
    local n_shift=1 # number of shifts in the outer loop; shift by 1 by default
    case "$1" in
        -i|--instance)
            shift
            instance=$1
            n_shift=2
            ;;
        -I|--image)
            shift
            image=$1
            n_shift=2
            ;;
        -c|--cmdline)
            shift
            cmdline=$1
            n_shift=2
            ;;
        -s|--system)
            shift
            system=$1
            n_shift=2
            ;;
        -g|--gdb)
            shift
            gdb=$1
            n_shift=2
            ;;
    esac
    return $n_shift
}

my_getopt "i:I:c:s:g:" "instance:,image:,cmdline:,system:,gdb:" "my_getopt_cont" "Test kernel instance using OS image with QEMU." "$(
cat <<END
[-i|--instance=<instance>] [-I|--image=<image>]
	[-c|--cmdline=<cmdline>] [-s|--system=<system>] [-g|--gdb=<gdb>]
END
)" "$(
cat <<END
-i	--instance		Maximal number of kernel instances to prepare (default: $instance).
-I	--image		Image (.img) under $LKHHIMAGE that hosts the OS (default: $image).
-c	--cmdline		Kernel cmdline (default: $cmdline).
-s	--system		QEMU system used for testing (default: $system).
-g	--gdb		QEMU GDB server device (refer to QEMU manpage; default: $gdb).
END
)" "$@"
ret=$?
eval set -- "$_getopt"
shift $ret

# sanity check
vecho 0 <<END
$(
dumpparam <<END1
$(
for name in instance image cmdline system gdb; do
    echo "$name=$(echo $(eval "echo \$$name"))"
done
)
END1
)
END

target_dir="$LKHH_ARENA/target/$instance"
[[ -d "$target_dir" ]] || die 1 <<END
ERROR: $target_dir does not exist; consider "lkhh-init -i $instance" first.
END

vmlinuz_path="$target_dir/vmlinuz"
initrd_path="$target_dir/initramfs-linux"
image_path="$LKHHIMAGE/$image.img"
uuid_path="$LKHHIMAGE/$image.uuid"

for i in "$vmlinuz_path" "$initrd_path" "$image_path" "$uuid_path"; do
    [[ -f "$i" ]] || die 1 <<END
ERROR: $i is not an existing regular file.
END
done

qemusystem="qemu-system-${system}"
for exe in "$qemusystem"; do
    type -p $exe >/dev/null || die 1 <<END
ERROR: $exe is not on PATH.
END
done

vecho 0 <<END
eval "'$qemusystem'" -kernel "'$vmlinuz_path'" -initrd "'$initrd_path'" -hda "'$image_path'" "${gdb:+-gdb '$gdb'}" -append "'root=$(cat "$uuid_path") $cmdline'" "$*"
END

unset IFS
eval "'$qemusystem'" -kernel "'$vmlinuz_path'" -initrd "'$initrd_path'" -hda "'$image_path'" "${gdb:+-gdb '$gdb'}" -append "'root=$(cat "$uuid_path") $cmdline'" "$*"
