#! /bin/bash

_rootdir=${_rootdir:-"$(dirname "$(readlink -f "$0")")"}
_ver="0.0.1-dev"
#_author="Wei Peng <me@1pengw.com>"

source "${_rootdir}/_shared_prologue"

#
# parameters
#
declare -i _instance=${_instance:-1}
declare _target=${_target:-modules}
declare -i _jobs=${_jobs:-$((2+$(nproc)))}
declare _moduleroot=${_moduleroot:-"$(readlink -f $PWD)"}
declare -i _install=${_install:-0}
declare -i _nbd=${_nbd:-1}

#
# getopt processing
#
function my_getopt_cont () {
    local n_shift=1 # number of shifts in the outer loop; shift by 1 by default
    case "$1" in
        -i|--instance)
            shift
            _instance=$1
            n_shift=2
            ;;
        -t|--target)
            shift
            _target=$1
            n_shift=2
            ;;
        -j|--jobs)
            shift
            _jobs=$1
            n_shift=2
            ;;
        -m|--moduleroot)
            shift
            _moduleroot=$1
            n_shift=2
            ;;
        -I|--install)
            _install=1
            n_shift=1
            ;;
        -n|--nbd)
            shift
            _nbd=$1
            n_shift=2
            ;;
    esac
    return $n_shift
}

my_getopt "i:t:j:m:In:" "instance:,target:,jobs:,moduleroot:,install,nbd:" "my_getopt_cont" "Make and optionally install modules into kernel instance." "$(
cat <<END
[-i|--instance=<instance>] [-t|--target=<target>] [-j|--jobs=<jobs>]
    [-m|--moduleroot=<moduleroot>] [-I|--install]
    [-n|--nbd=<nbd>] 
END
)" "$(
cat <<END
-i	--instance		Maximal number of kernel instances to prepare (default: $_instance).
-t	--target		Makefile target to make (default: $_target).
-j	--jobs		Number of parallel make jobs (default: $_jobs).
-m	--moduleroot		Root directory of the module, where "Makefile" is found (default: $_moduleroot).
-I	--install		Install the module (default: $_install).
-n	--nbd		Network Block Device (NBD) that has loop-mounted the OS image (default: $_nbd).
END
)" "$@"
ret=$?
eval set -- "$_getopt"
shift $ret 

# sanity check
vecho 0 <<END
$(
dumpparam <<END1
$(
for name in instance target jobs moduleroot; do
    echo "$name=$(echo $(eval "echo \$_$name"))"
done
)
END1
)
END

build_dir="$LKHH_ARENA/build/$_instance"

[[ -d "$build_dir" ]] || die 1 <<END
ERROR: $build_dir does not exist; consider "lkhh-init -i $_instance" first.
END

target_dir="$LKHH_ARENA/target/$_instance"

[[ -d "$target_dir" ]] || die 1 <<END
ERROR: $target_dir does not exist; consider "lkhh-init -i $_instance" first.
END

moduleroot="$(readlink -f "$_moduleroot")"

[[ -d "$moduleroot" ]] || die 1 <<END
ERROR: $moduleroot does not exist.
END

vecho 0 <<END
make -C "$build_dir" -j "$_jobs" "O=$build_dir" "M=$moduleroot" "$@" "$_target"
END

make -C "$build_dir" -j "$_jobs" "O=$build_dir" "M=$moduleroot" "$@" "$_target"

# If install is requested.
if (( _install > 0 )); then

    vecho 0 <<END
make -C "$build_dir" -j "$_jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modules_install
END

    make -C "$build_dir" -j "$_jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modules_install

    mnt="$LKHH_IMAGE/mnt/$_nbd"

    if [[ -d "$mnt" ]] && mountpoint "$mnt" >/dev/null; then
        target_dir="$mnt/usr"

        vecho 0 <<END
        sudo make -C "$build_dir" -j "$_jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modules_install
END

        sudo make -C "$build_dir" -j "$_jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modules_install
    fi
fi
