#! /bin/bash

_rootdir=${_rootdir:-"$(dirname "$(readlink -f "$0")")"}
_ver="0.0.1-dev"
#_author="Wei Peng <me@1pengw.com>"

source "${_rootdir}/_shared_prologue"

#
# parameters
#
declare -i instance=${instance:-1}
declare target=${target:-modules}
declare -i jobs=${jobs:-$((2+$(nproc)))}
declare moduleroot=${moduleroot:-"$(readlink -f $PWD)"}
declare -i install=${install:-0}
declare -i nbd=${nbd:-1}

#
# getopt processing
#
function my_getopt_cont () {
    local n_shift=1 # number of shifts in the outer loop; shift by 1 by default
    case "$1" in
        -i|--instance)
            shift
            instance=$1
            n_shift=2
            ;;
        -t|--target)
            shift
            target=$1
            n_shift=2
            ;;
        -j|--jobs)
            shift
            jobs=$1
            n_shift=2
            ;;
        -m|--moduleroot)
            shift
            moduleroot=$1
            n_shift=2
            ;;
        -I|--install)
            install=1
            n_shift=1
            ;;
        -n|--nbd)
            shift
            nbd=$1
            n_shift=2
            ;;
    esac
    return $n_shift
}

my_getopt "i:t:j:m:In:" "instance:,target:,jobs:,moduleroot:,install,nbd:" "my_getopt_cont" "Make and optionally install modules into kernel instance." "$(
cat <<END
[-i|--instance=<instance>] [-t|--target=<target>] [-j|--jobs=<jobs>]
    [-m|--moduleroot=<moduleroot>] [-I|--install]
    [-n|--nbd=<nbd>] 
END
)" "$(
cat <<END
-i	--instance		Maximal number of kernel instances to prepare (default: $instance).
-t	--target		Makefile target to make (default: $target).
-j	--jobs		Number of parallel make jobs (default: $jobs).
-m	--moduleroot		Root directory of the module, where "Makefile" is found (default: $moduleroot).
-I	--install		Install the module (default: $install).
-n	--nbd		Network Block Device (NBD) that has loop-mounted the OS image (default: $nbd).
END
)" "$@"
ret=$?
eval set -- "$_getopt"
shift $ret 

# sanity check
vecho 0 <<END
$(
dumpparam <<END1
$(
for name in instance target jobs moduleroot; do
    echo "$name=$(echo $(eval "echo \$_$name"))"
done
)
END1
)
END

build_dir="$LKHH_ARENA/build/$instance"

[[ -d "$build_dir" ]] || die 1 <<END
ERROR: $build_dir does not exist; consider "lkhh-init -i $instance" first.
END

target_dir="$LKHH_ARENA/target/$instance"

[[ -d "$target_dir" ]] || die 1 <<END
ERROR: $target_dir does not exist; consider "lkhh-init -i $instance" first.
END

moduleroot="$(readlink -f "$moduleroot")"

[[ -d "$moduleroot" ]] || die 1 <<END
ERROR: $moduleroot does not exist.
END

vecho 0 <<END
make -C "$build_dir" -j "$jobs" "O=$build_dir" "M=$moduleroot" "$@" "$target"
END

make -C "$build_dir" -j "$jobs" "O=$build_dir" "M=$moduleroot" "$@" "$target"

# If install is requested.
if (( install > 0 )); then

    vecho 0 <<END
make -C "$build_dir" -j "$jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modulesinstall
END

    make -C "$build_dir" -j "$jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modulesinstall

    mnt="$LKHH_IMAGE/mnt/$nbd"

    if [[ -d "$mnt" ]] && mountpoint "$mnt" >/dev/null; then
        target_dir="$mnt/usr"

        vecho 0 <<END
        sudo make -C "$build_dir" -j "$jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modulesinstall
END

        sudo make -C "$build_dir" -j "$jobs" "O=$build_dir" "M=$moduleroot" "INSTALL_MOD_PATH=$target_dir" "$@" modulesinstall
    fi
fi
