#! /bin/bash

_rootdir=${_rootdir:-"$(dirname "$(readlink -f "$0")")"}
_ver="0.0.1-dev"
#_author="Wei Peng <me@1pengw.com>"

source "${_rootdir}/_shared_prologue"

#
# parameters
#
declare -i _instance=${_instance:-1}
declare _target=${_target:-help}
declare -i _jobs=${_jobs:-$((2+$(nproc)))}

# see also: http://nickdesaulniers.github.io/blog/2018/06/02/speeding-up-linux-kernel-builds-with-ccache/
declare -i _deterministic=${_deterministic:-0}

#
# getopt processing
#
function my_getopt_cont () {
    local n_shift=1 # number of shifts in the outer loop; shift by 1 by default
    case "$1" in
        -i|--instance)
            shift
            _instance=$1
            n_shift=2
            ;;
        -t|--target)
            shift
            _target=$1
            n_shift=2
            ;;
        -j|--jobs)
            shift
            _jobs=$1
            n_shift=2
            ;;
        -d|--deterministic)
            _deterministic=1
            n_shift=1
            ;;
    esac
    return $n_shift
}

my_getopt "i:t:j:d" "instance:,target:,jobs:,deterministic" "my_getopt_cont" "Make kernel instance." "$(
cat <<END
[-i|--instance=<instance>] [-t|--target=<target>] [-j|--jobs=<jobs>]
	[-d|--deterministic]
END
)" "$(
cat <<END
-i	--instance		Maximal number of kernel instances to prepare (default: $_instance).
-t	--target		Makefile target to make (default: $_target).
-j	--jobs		Number of parallel make jobs (default: $_jobs).
-d	--deterministic		Deterministic build to leverage, e.g., ccache (default: $_deterministic).
END
)" "$@"
ret=$?
eval set -- "$_getopt"
shift $ret 

# sanity check
vecho 0 <<END
$(
dumpparam <<END1
$(
for name in instance target jobs deterministic; do
    echo "$name=$(echo $(eval "echo \$_$name"))"
done
)
END1
)
END

build_dir="$LKHH_ARENA/build/$_instance"

[[ -d "$build_dir" ]] || die 1 <<END
ERROR: $build_dir does not exist; consider "lkhh-init -i $_instance" first.
END

vecho 0 <<END
make "O=$build_dir" -j $_jobs "$@" "$_target"
END

if (( deterministic > 0 )); then
    export KBUILD_BUILD_TIMESTAMP="1991-08-25" # Happy Birthday, Linux
fi

make "O=$build_dir" -j $_jobs "$@" "$_target"
