#! /bin/bash

_rootdir=${_rootdir:-"$(dirname "$(readlink -f "$0")")"}
_ver="0.0.1-dev"
#_author="Wei Peng <me@1pengw.com>"

source "${_rootdir}/_shared_prologue"

#
# parameters
#
declare -i _instance=${_instance:-1}
declare -i _download=${_download:-0}

#
# getopt processing
#
function my_getopt_cont () {
    n_shift=1 # number of shifts in the outer loop; shift by 1 by default
    case "$1" in
        -i|--instance)
            shift
            _instance=$1
            n_shift=2
            ;;
        -d|--download)
            _download=1
            n_shift=1
            ;;
    esac
    return $n_shift
}

my_getopt "i:d" "instance:,download" "my_getopt_cont" "One-time initialization for Linux Kernel Hacking Helper (LKHH)." "$(
cat <<END
[-i|--instance=<instance>] [-d|--download]
END
)" "$(
cat <<END
-i	--instance		Maximal number of kernel instances to prepare (default: $_instance).
-d	--download		Download an OS image for testing (default: $_download).
END
)" "$@"
ret=$?
eval set -- "$_getopt"
shift $ret

# sanity check
vecho 0 <<END
$(
dumpparam <<END1
$(
for name in instance download; do
    echo "$name=$(echo $(eval "echo \$_$name"))"
done
)
END1
)
END

mkdir -p "$LKHH_ARENA" || die 1 <<END
Fail to create $LKHH_ARENA.
END


eval mkdir -p $LKHH_ARENA/{target,build}/{1..$_instance} "$LKHH_ARENA/aux" "$LKHH_IMAGE/mnt" || >/dev/stderr vecho 0 <<END
ERROR: Fail to create certain base directories.
END

file="$LKHH_BIN/aux/mkinitcpio.conf"
dir="$LKHH_ARENA/aux"

cp -f "$file" "$dir" || >/dev/stderr vecho 0 <<END
ERROR: Fail to copy $file into $dir.
END

if (( _download > 0 )); then
    pushd $LKHH_IMAGE || die 1 <<END
Fail to cd into $LKHH_IMAGE.
END
    if type -p aria2c; then
        aria2c -j 10 -x 10 -Z -- https://github.com/pw4ever/linux-kernel-hacking-helper/releases/download/arch-clean/arch-clean.tar.a{a,b,c,d,e,f} && cat arch-clean.tar.a{a,b,c,d,e,f} | tar xvf -
    elif type -p wget; then
        wget -- https://github.com/pw4ever/linux-kernel-hacking-helper/releases/download/arch-clean/arch-clean.tar.a{a,b,c,d,e,f} && cat arch-clean.tar.a{a,b,c,d,e,f} | tar xvf -
    fi
    popd
fi
